proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
  specs:
  - id: 01_app
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-q", "-e", "shiny::runApp('/root/shiny_app_example')"]
    container-image: ghcr.io/xingyaoc/shiny_app_example:latest
    container-network: sp-example-net
  - id: 02_app
    container-cmd: ["R", "-q", "-e", "shiny::runApp('/root/shiny_app_example2')"]
    container-image: ghcr.io/xingyaoc/shiny_app_example2:latest
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log
