name: publish

on:
  push:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  publish-shinyproxy_prototype_example:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: spatreitm
        password:   ${{ secrets.GITHUB_TOKEN }} 

    - name: Build the Shinyproxy prototype Docker image
      run: |
        docker build . --tag ghcr.io/xingyaoc/shinyproxy_proto:latest
        docker push ghcr.io/xingyaoc/shinyproxy_proto:latest
